ost-cas-fee-adv-23-24/design-system-component-library-clada

.storybook/main.js, .storybook/preview.js, postcss.config.js, src/components/button.tsx, src/index.css, tailwind.config.js
Setup and initial configuration for Tailwind
=> chore: setup tailwind

.github/workflows/Semantic-Release.yml
Correct the semantic release pipeline to select the correct branch.
=> chore: correct semantic pipeline

package.json
Add the "release" property to the package json for the semantic release pipeline.
=> chore: add release branch configuration

package.json
Rename tailwind config import inside the package json file.
=> fix: rename tailwind config import

package.json
Reconfigure the output in the dist folder to be usable.
=> fix: reconfigure build output

.eslintrc.js, .github/workflows/Lint.yml, .gitignore, .husky/pre-commit, package-lock.json, package.json
Add eslint to the project with automatic linting on local instance as well as on creating a pull request.
=> chore: add linting to project

.gitignore, .storybook/main.js, src/components/button/button.stories.tsx, src/components/button/button.tsx, src/components/button/index.ts, src/docs/design-tokens/colors.mdx, src/docs/design-tokens/spacing.mdx, src/docs/introduction.mdx, tailwind.config.js
This pull request adds the first base design tokens for the clada design system.
Following are included:
- Introduction doc
- Colors
- Gradients
- Spacing
=> feat: add foundation for design system

README.md, src/docs/design-tokens/typography.mdx, src/index.css, tailwind.config.js
This pull request adds the poppins font to the design system. This includes the font itself, the tailwind configuration, license credits to the author of the font and the corresponding storybook documentation.
=> feat: add typography

src/docs/design-tokens/borders.mdx, src/docs/design-tokens/colors.mdx, src/index.css, tailwind.config.js
1 Added Border definitions and adjusted existing foundation files to reflect borders.
2 Set Font-Family to Poppins for all of Storybook
3 Adjusted foundation files for consistency
=> feat: add border foundations

package.json
add to build script to rename commonJS index file for compatibility
=> chore: rename cjs index file extension js to cjs

.storybook/preview.js, .storybook/storybook.css
Applies the mumble font to storybook text.
=> feat: add mumble font to storybook

.eslintrc.js, package-lock.json, package.json, src/components/index.ts, src/components/input/index.ts, src/components/input/input-password.tsx, src/components/input/input-passwort.stories.tsx, src/components/input/input.stories.tsx, src/components/input/input.tsx
This pull request introduces the new Input and PasswordInput components, expanding our component library.
=> feature: add input

src/components/index.ts, src/components/input/input.tsx, src/components/textarea/index.ts, src/components/textarea/textarea.stories.tsx, src/components/textarea/textarea.tsx
This pullrequest adds the textarea component to the design system.
=> feat: add textarea component

tsconfig.json
This pull request changes the build so that the *.stories.tsx files are not included anymore.
=> chore: exclude stories from build

src/components/index.ts, src/components/link/index.ts, src/components/link/link.stories.tsx, src/components/link/link.tsx
This pull request adds the link component to the design system.
=> feat: add link

src/components/icon-button/icon-button.stories.tsx, src/components/icon-button/icon-button.tsx, src/components/icon-button/index.ts, src/components/icons/iconUtils.ts, src/components/index.ts, tailwind.config.js
This pull request adds the icon button component to the designs system.
=> feat: add icon button

src/components/comment-button/comment-button.stories.tsx, src/components/comment-button/comment-button.tsx, src/components/copy-link-button/copy-link-button.stories.tsx, src/components/copy-link-button/copy-link-button.tsx, src/components/like-button/like-button.stories.tsx, src/components/like-button/like-button.tsx
<h2>Pull Request: Refactoring Hardcoded Strings to Labels</h2>
<p>
<strong>Overview:</strong><br>
This pull request introduces changes that remove hardcoded strings from the codebase, replacing them with customizable label inputs. This enhancement aims to improve the flexibility and maintainability of the user interface components.
</p>
<hr>
<h3>Key Changes:</h3>
<ul>
<li>Replaced hardcoded strings with label props in the LikeButton, CopyLinkButton and  CommentButton components.</li>
<li>Updated propTypes to reflect the new changes.</li>
<li>Adjusted Storybook stories to accommodate the new props.</li>
</ul>
<hr>
<h3>Impact:</h3>
<p>
These changes allow for greater customization and localization of UI components, making them more adaptable for various use cases. This update requires …
=> feat: remove hardcoded strings

src/components/index.ts
We forgot to export the interaction buttons
Fix: The interaction buttons exports are hereby added.
=> fix: add missing exports

src/components/logo/logo.tsx
In this pr the logo is resized to fit the design for the platform.
=> fix: resize logo

src/components/logo/logo.tsx
Improve Logo Text Responsiveness
=> feat: no flex-rows on medium screen - hide text
